name: Build & Release Rust Binaries

on:
  push:
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x86_64, aarch64]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Install OpenCL headers
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y ocl-icd-opencl-dev
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            vcpkg install opencl
            echo "C:\vcpkg\installed\x64-windows\include" >> $GITHUB_PATH
            echo "C:\vcpkg\installed\x64-windows\lib" >> $GITHUB_PATH
            echo 'INCLUDE="C:\vcpkg\installed\x64-windows\include;%INCLUDE%"' >> $GITHUB_ENV
            echo 'LIB="C:\vcpkg\installed\x64-windows\lib;%LIB%"' >> $GITHUB_ENV
          fi

      - name: Debug
        run: |
          echo $INCLUDE
          echo $LIB

      - name: Install GHC for Futhark
        uses: haskell-actions/setup@v2

      - name: Set Rust target triple
        id: target
        run: |
          case "${{ matrix.os }}_${{ matrix.arch }}" in
            ubuntu-latest_x86_64)    echo "target_triple=x86_64-unknown-linux-gnu" >> $GITHUB_OUTPUT ;;
            ubuntu-latest_aarch64)   echo "target_triple=aarch64-unknown-linux-gnu" >> $GITHUB_OUTPUT ;;
            windows-latest_x86_64)   echo "target_triple=x86_64-pc-windows-msvc" >> $GITHUB_OUTPUT ;;
            windows-latest_aarch64)  echo "target_triple=aarch64-pc-windows-msvc" >> $GITHUB_OUTPUT ;;
            *) echo "Unsupported combination" ; exit 1 ;;
          esac

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ steps.target.outputs.target_triple }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Futhark build
        uses: actions/cache@v4
        if: always()
        with:
          path: |
            futhark
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ runner.arch }}-futhark

      - name: Install Futhark
        run: |
          if [ ! -d "futhark" ]; then
            git clone https://github.com/diku-dk/futhark.git
          fi
          cd futhark
          make configure
          make build
          echo $(dirname "$(cabal -v0 list-bin exe:futhark)") >> $GITHUB_PATH

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Set version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/}"
          CLEAN_VERSION="${TAG_VERSION#v}" # strip leading 'v'
          echo "Setting Cargo.toml version to $CLEAN_VERSION"
          # Update version using sed (POSIX-safe)
          sed -i.bak -E "s/^version = .*/version = \"${CLEAN_VERSION}\"/" Cargo.toml
          rm -f Cargo.toml.bak

      - name: Build release
        env:
          CARGO_TARGET_DIR: target/${{ matrix.os }}-${{ matrix.arch }}
        run: CC=clang RUSTFLAGS=-Awarnings cargo build --release -vv

      - name: Package artifact
        run: |
          mkdir -p dist
          target_dir="target/${{ matrix.os }}-${{ matrix.arch }}/release"
          BIN_NAME="duosplit"
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then BIN_NAME="${BIN_NAME}.exe"; fi
          cp "$target_dir/$BIN_NAME" "dist/${BIN_NAME}-${{ matrix.os }}-${{ matrix.arch }}"
          ls -lh dist/

      - name: Breakpoint if failed
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: Seggan

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts from all build jobs
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
